### ISSUE TITLE
TypeError: ICalendar is not a constructor error

### ISSUE THREAD

**Issue by asunar** [jshor/datebook#137]
Getting an ICalendar is not a constructor error when following the example usage from the website.
Can anyone see what I am doing wrong?

`npm i datebook --save`

package.json:
```
  "dependencies": {
    "aws-sdk": "^2.812.0",
    "datebook": "^6.1.1"
  },
```

```
const ICalendar = require('datebook')

const icalendar = new ICalendar({
  title: 'Happy Hour',
  location: 'The Bar, New York, NY',
  description: 'Let\'s blow off some steam from our weekly deployments to enjoy a tall cold one!',
  start: new Date('2020-07-04T19:00:00'),
  end: new Date('2020-07-04T23:30:00'),
  recurrence: {
    frequency: 'WEEKLY',
    interval: 2
  }
})
```
```
TypeError: ICalendar is not a constructor
    at Runtime.handler (/var/task/app.js:43:27)
    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)
```

**Comment by asunar** [comment]
Same error with yarn

**Comment by asunar** [comment]
This works.

```
const datebook = require('datebook');
const icalendar = new datebook.ICalendar({
  title: 'Happy Hour',
  location: 'The Bar, New York, NY',
  description: 'Let\'s blow off some steam from our weekly deployments to enjoy a tall cold one!',
  start: new Date('2020-07-04T19:00:00'),
  end: new Date('2020-07-04T23:30:00'),
  recurrence: {
    frequency: 'WEEKLY',
    interval: 2
  }
}); 
```

**Comment by jshor** [comment]
Hi @asunar 

Yes you are correct. The library exports four classes: `GoogleCalendar`, `YahooCalendar`, `OutlookCalendar`, and `ICalendar` to render calendars. More documentation on each of these classes and their members can be found here: https://datebook.dev/docs/
