### ISSUE TITLE
Syntax Error when building with Sveltekit

### ISSUE THREAD

**Issue by vexkiddy** [jshor/datebook#213]
When using `datebook` in production with `sveltekit` and using `npm run build` i get the following syntax error in my terminal. However when I run with `npm run dev` the project runs totally fine. Any ideas why this could be happening ? I've tried what it suggests and this just totally breaks the project in both dev and production :( 

```
import { GoogleCalendar, OutlookCalendar, YahooCalendar } from "datebook";
          ^^^^^^^^^^^^^^
SyntaxError: Named export 'GoogleCalendar' not found. The requested module 'datebook' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'datebook';
const { GoogleCalendar, OutlookCalendar, YahooCalendar } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
    at async Module.component (file:///Users/username/Sites/yeeldz-v3/.svelte-kit/output/server/nodes/0.js:4:39)
    at async Promise.all (index 0)
    at async render_response (file:///Users/username/Sites/yeeldz-v3/.svelte-kit/output/server/index.js:1062:19)
    at async render_page (file:///Users/username/Sites/yeeldz-v3/.svelte-kit/output/server/index.js:1569:12)
    at async resolve (file:///Users/username/Sites/yeeldz-v3/.svelte-kit/output/server/index.js:2250:22)
    at async respond (file:///Users/username/Sites/yeeldz-v3/.svelte-kit/output/server/index.js:2152:22)
    at async file:///Users/username/Sites/yeeldz-v3/node_modules/@sveltejs/kit/src/exports/vite/preview/index.js:145:5

```

**Comment by vexkiddy** [comment]
So found this thread about something similar happening with another library.. it looks like `datebook` is using `UMD` under `main` in the package.json, which apparently node doesn't like ? More info can be found at the end of this thread, maybe its useful ? https://github.com/sveltejs/kit/issues/5325

**Comment by jshor** [comment]
There's an ESM version of Datebook [in the dist](https://github.com/jshor/datebook/blob/main/package.json#L25). But if the `module` entry isn't being picked up by your build, you could try referencing the ESM build directly in your import:

```js
import { GoogleCalendar, OutlookCalendar, YahooCalendar } from "datebook/dist/datebook.esm.min.js";
```

**Comment by vexkiddy** [comment]
hiya @jshor yeah i've tried that and get the same issues. However when I copy datebook.esm.min.js locally and run my build it then works. It's very odd :(

**Comment by jshor** [comment]
@vexkiddy could you provide a repo to reproduce the issue?

**Comment by vexkiddy** [comment]
sure! made you a version which you can clone and try out here: https://github.com/vexkiddy/datebook-sveltekit-issues

**Comment by jshor** [comment]
Thanks @vexkiddy, I believe it should be fixed now. Give v7.1.2 a try and see if it resolves your issue

**Comment by vexkiddy** [comment]
@jshor amazing! that works like a dream! thanks so much for fixing this so quickly! :D
